#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#
# This script bootstraps into Bash. The shebang is only for portability.
# For more information, see the Bash library > Bootstrapping section of
# the SST manual.
#

# Load the prelude.
case $0 in /*) x=$0 ;; *) x=./$0 ;; esac
x=`dirname "$x"` || exit $?
set -e || exit $?
. "$x"/../../preludes/gitlab-ci.bash

sst_import_function \
  sst_csf \
  sst_extract_archive \
  sst_find_dist_archive \
;

dist_archive=$rundir/$(sst_find_dist_archive)
readonly dist_archive

cd "$tmpdir"
sst_extract_archive "$dist_archive"
cd *
install/on-ubuntu
make V=1 VERBOSE=1 distcheck
