#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#
# This script bootstraps into Bash. The shebang is only for portability.
# For more information, see the Bash library > Bootstrapping section of
# the SST manual.
#

# Load the prelude.
case $0 in /*) x=$0 ;; *) x=./$0 ;; esac
x=`dirname "$x"` || exit $?
set -e || exit $?
. "$x"/../../preludes/gitlab-ci.bash

apt-get -qy update

apt-get -qy install \
  default-jdk \
  default-jre \
  doxygen \
  g++ \
  gcc \
  git \
  make \
  texinfo \
  texlive \
  texlive-latex-extra \
  wget \
;

mkdir $tmpdir/x
cd $tmpdir/x
tar xf $rundir/*.tar.gz
cd *

./configure \
  ASCIIDOCTOR='build-aux/adock asciidoctor' \
;

make \
  doc/manual/sst.html \
  pages \
;

mv -f doc/manual/sst.html "$rundir"/doc/manual
mv -f doc/*-pages "$rundir"/doc
