#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#
# This script bootstraps into Bash. The shebang is only for portability.
# For more information, see the Bash library > Bootstrapping section of
# the SST manual.
#

# Load the prelude.
case $0 in /*) x=$0 ;; *) x=./$0 ;; esac
x=`dirname "$x"` || exit $?
set -e || exit $?
. "$x"/../../preludes/gitlab-ci.bash

f=$(sst_find_dist_archive | sst_csf)
sst_csf f
cd "$tmpdir"
tar xzf "$rundir/$f"
cd *

install/$1
make V=1 VERBOSE=1 check
make V=1 VERBOSE=1 installcheck
