#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#
# This script bootstraps into Bash. The shebang is only for portability.
# For more information, see the Bash library > Bootstrapping section of
# the SST manual.
#

# Load the prelude.
case $0 in /*) x=$0 ;; *) x=./$0 ;; esac
x=`dirname "$x"` || exit $?
set -e || exit $?
. "$x"/../../preludes/gitlab-ci.bash

sst_install_utility \
  cat \
  gawk \
  git \
  make \
  mv \
;

readonly dist_dir="$1"
readonly repo_dir="$2"

gawk \
  -f "$repo_dir"/doc/readme/flatten.gawk \
  -v input_dir=. \
  -v script_file="$repo_dir"/doc/readme/flatten.gawk \
  README.adoc \
  >"$tmpdir"/README.adoc \
;
cat "$tmpdir"/README.adoc >README.adoc

mkdir "$tmpdir"/foo
(
  cd "$tmpdir"/foo
  "$dist_dir"/configure
  make build-aux/downloads/gpl-3.0.txt
)
cat "$tmpdir"/foo/build-aux/downloads/gpl-3.0.txt >COPYING

git add -u
