#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#
# This script bootstraps into Bash. The shebang is only for portability.
# For more information, see the Bash library > Bootstrapping section of
# the SST manual.
#

#
# The following files are very similar:
#
#   src/bash/scripts/gitlab-ci/rpm-centos-7-x86-64
#   src/bash/scripts/gitlab-ci/rpm-rhel-7-x86-64
#
# You should keep these files in sync.
#

# Load the prelude.
case $0 in /*) x=$0 ;; *) x=./$0 ;; esac
x=`dirname "$x"` || exit $?
set -e || exit $?
. "$x"/../../preludes/gitlab-ci.bash

apt-get -qy update

apt-get -qy install \
  gcc \
  make \
  wget \
;

x=$(basename sst-*.tar.gz .tar.gz)
tar xf $x.tar.gz
mv $x.tar.* $x
cd $x
./configure
make \
  rpm/centos-7/x86_64 \
;
