#! /bin/sh -
#
# For the copyright information for this file, please search up the
# directory tree for the first COPYING file.
#
# This script bootstraps into Bash. The shebang is only for portability.
# For more information, see the Bash library > Bootstrapping section of
# the SST manual.
#

# Load the prelude.
case $0 in /*) x=$0 ;; *) x=./$0 ;; esac
x=`dirname "$x"` || exit $?
set -e || exit $?
. "$x"/../../preludes/gitlab-ci.bash

sst_install_utility gpg2

sst_expect_argument_count $# 0

# Verify that the prelude loaded a GPG key.
if [[ ! "${GPG_SECRET_KEY+x}" ]]; then
  sst_barf 'GPG_SECRET_KEY is unset'
elif [[ ! "$GPG_SECRET_KEY" ]]; then
  sst_barf 'GPG_SECRET_KEY is empty'
fi

# Sign each artifact.
artifacts=()
x=$(sst_quote <<<"s/'/&\\\\&&/g; 1s/^/artifacts+=('/; \$s/\$/');/")
x=$(git ls-files -o -z | xargs -0 -n 1 bash -c "sed $x <<<\"\$0\"")
eval "$x"
for artifact in "${artifacts[@]}"; do
  artifact=$(sst_dot_slash "$artifact" | sst_csf)
  sst_csf artifact
  gpg2 -b -o "$artifact.sig" "$artifact"
done
