//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#{xj7vricq_id}]
= The `{xj7vricq_name}` type

[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/{xj7vricq_name_c1}[sst/catalog/{xj7vricq_name_c1},window=_blank]>
namespace sst {

struct {xj7vricq_c1} {};

}
----

The `{xj7vricq}` type is an empty type that can be used to help
distinguish between compile-time and run-time operations.

.{empty}
[example]
====
Consider two types `A` and `B` with the same function `f`, but only one
of the functions can be evaluated at compile-time.
The types can provide a type alias `f_phase` to help distinguish this:

.`sst-example-{example-number}.cpp`
[source,cpp,subs="{sst_subs_source}"]
----
#include <iostream>

#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/compile_time_tag.hpp[sst/catalog/compile_time_tag.hpp,window=_blank]>
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/run_time_tag.hpp[sst/catalog/run_time_tag.hpp,window=_blank]>

struct A {
  static constexpr int f() { return 0; }
  using f_phase = {cl_sst_compile_time_tag};
};

struct B {
  static int f() { return 1; }
  using f_phase = {cl_sst_run_time_tag};
};

template<class T>
void g(char const * const name, sst::compile_time_tag) {
  std::cout << name << "::f() is compile-time.\n";
}

template<class T>
void g(char const * const name, sst::run_time_tag) {
  std::cout << name << "::f() is run-time.\n";
}

template<class T>
void g(char const * const name) {
  g<T>(name, typename T::f_phase());
}

int main() {
  g<A>("A");
  g<B>("B");
}
----

.Output
[listing,subs="{sst_subs_source}"]
----
A::f() is compile-time.
B::f() is run-time.
----

include::cl_cpp_compilation_command.adoc[]
====

//
