//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

//----------------------------------------------------------------------
ifdef::define_attributes[]
ifndef::SECTIONS_CL_SST_SOCKET_EXAMPLES_ADOC[]
:SECTIONS_CL_SST_SOCKET_EXAMPLES_ADOC:
//----------------------------------------------------------------------

:cl_sst_socket_examples_id: cl_sst_socket_examples
:cl_sst_socket_examples_title: Examples

//----------------------------------------------------------------------
endif::[]
endif::[]
ifndef::define_attributes[]
//----------------------------------------------------------------------

[#{cl_sst_socket_examples_id}]
= {cl_sst_socket_examples_title}

[source,cpp,subs="{sst_subs_source}"]
----
#include <future>
#include <iostream>
#include <ostream>
#include <string>

#include <sst/catalog/socket.hpp>
#include <sst/catalog/socket_shutdown.hpp>

int main(int argc, char ** argv) {

  // Initialize the socket library, if necessary.
  sst::socket_library_scope socket_library_scope;

  sst::socket socket;
  if (argc > 1) {
    // Run as the server if there's a command-line argument.
    sst::socket listener;
    listener.reuseaddr(true);
    listener.listen("127.0.0.1", 12345);
    socket = listener.accept();
  } else {
    // Run as the client if there's no command-line argument.
    socket.connect("127.0.0.1", 12345);
  }

  // In a background thread, read data from standard input and send it
  // over the socket.
  auto background = std::async(std::launch::async, [&socket] {
    std::string line;
    while (std::getline(std::cin, line)) {
      line += '\n';
      socket.send_exactly(&line[0], line.size());
    }
    socket.shutdown(sst::socket_shutdown::send());
  });

  // In the main thread, receive data from the socket and write it to
  // standard output.
  std::string buf;
  while (!socket.eof()) {
    buf.resize(100);
    auto const n = socket.recv_some(&buf[0], buf.size());
    buf.resize(n);
    std::cout << buf << std::flush;
  }

  // Wait for the background thread to finish.
  background.get();

}
----

//----------------------------------------------------------------------
endif::[]
