//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

//----------------------------------------------------------------------
ifdef::define_attributes[]
ifndef::SECTIONS_CL_SST_EXPAND_ADOC[]
:SECTIONS_CL_SST_EXPAND_ADOC:
//----------------------------------------------------------------------

:cl_SST_EXPAND_name0: SST_EXPAND

:cl_SST_EXPAND_id: cl-SST-EXPAND
:cl_SST_EXPAND_url: sections/cl_SST_EXPAND.adoc#{cl_SST_EXPAND_id}

:cl_SST_EXPAND_chop0: xref:{cl_SST_EXPAND_url}[{cl_SST_EXPAND_name0}]

:cl_SST_EXPAND: {cl_SST_EXPAND_chop0}

:cl_sst_catalog_SST_EXPAND_h_url: {repo_browser_url}/src/c-cpp/include/sst/catalog/SST_EXPAND.h
:cl_sst_catalog_SST_EXPAND_h: link:{cl_sst_catalog_SST_EXPAND_h_url}[sst/catalog/SST_EXPAND.h,window=_blank]

//----------------------------------------------------------------------
endif::[]
endif::[]
ifndef::define_attributes[]
//----------------------------------------------------------------------

[#{cl_SST_EXPAND_id}]
= The `{cl_SST_EXPAND_name0}` macro

.C or {cpp}
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/SST_EXPAND.h[sst/catalog/SST_EXPAND.h,window=_blank]>

#define {cl_SST_EXPAND}(...) pass:a,m[{cl_VA_ARGS_c}]
----

The `{cl_SST_EXPAND}` macro expands to its argument list unchanged.

Note that calling the `{cl_SST_EXPAND}` macro without any arguments,
i.e., writing `{cl_SST_EXPAND}()`, is well-defined even when
`{cl_VA_OPT_c}` is not supported.
In this case, the call is interpreted as having one argument that
consists of no preprocessing tokens.

.{empty}
[example]
====
Because of the way the preprocessor works, macro arguments that contain
commas must be enclosed in parentheses, otherwise the commas will be
interpreted as macro argument separators.
If the argument is an expression, then the extra parentheses are
harmless, but if the argument is something else, then the extra
parentheses will generally cause a syntax error.

For example, if `F(T)` is a macro that takes a type name `T`, then
`F({cl_std_map}<int, int>)` won't work as expected, as the comma is
interpreted as a macro argument separator and the call is therefore
trying to pass two arguments: `{cl_std_map}<int` and `int>`.
Writing `F++((++{cl_std_map}<int, int>))` fixes the argument count
issue, but now the type name is enclosed in parentheses, which will
generally cause a syntax error.

One way to resolve this is to declare a type alias for
`{cl_std_map}<int, int>` and pass the alias to the macro.
However, this is not a general solution, as it only works in the
specific case where the argument is a type name.

A general way to resolve this is to require the arguments to always be
enclosed in parentheses and use the `{cl_SST_EXPAND}` macro to remove
the parentheses.

.`sst-example-{example-number}.cpp`
[source,subs="{sst_subs_source}"]
----
#include <{cl_include_iostream}>
#include <{cl_include_map}>
#include <{cl_include_type_traits}>

#include <{cl_sst_catalog_SST_EXPAND_h}>

// When calling this macro, each argument should always be enclosed in
// parentheses, which {cl_SST_EXPAND} will then remove.
#define SAME(A, B) ({cl_std_is_same}<{cl_SST_EXPAND} A, {cl_SST_EXPAND} B>::value)

int {cl_cpp_main}() {
  {cl_std_cout} << SAME++((++{cl_std_map}<int, int>), ({cl_std_map}<int, int>)) << "\n";
  return 0;
}
----

.Output
[listing,subs="{sst_subs_source}"]
----
1
----
====

//----------------------------------------------------------------------
endif::[]
