#
# This file was generated by GATBPS 0.1.0-5965+gf7915071, which was
# released on 2022-12-17. Before changing it, make sure
# you're doing the right thing. Depending on how GATBPS
# is being used, your changes may be automatically lost.
# A short description of this file follows.
#
# Special file: gen-configure.sh
#
# For more information, see the GATBPS manual.
#

case ${GATBPS_GEN_CONFIGURE_BOOTSTRAP-} in
  '')
    cat <<'EOF2' || exit $?
configure: preparing environment for code generation
EOF2

    xs=GATBPS_GEN_CONFIGURE_BOOTSTRAP=x
    for x in \
      GATBPS_TIMESTAMPS_NORMALIZED \
      PATH \
      TEMP \
      TMP \
    ; do
      eval 'xs=$xs${'$x'+ '$x'=\"\$'$x'\"}'
    done

    eval 'env -i '"$xs"' sh - "$0"'
    exit $?
  ;;
esac

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
