\input texinfo
@setfilename sst.info

@ifxml
@c
@c For the copyright information for this file, please search up the
@c directory tree for the first COPYING file.
@c
@end ifxml

@ifclear insertascii
@documentencoding UTF-8
@end ifclear

@documentlanguage en

@include PACKAGEVERSION.texi

@settitle SST @value{PACKAGEVERSION} Manual

@include PACKAGEDATE.texi
@include copying-block.texi
@include math.texi

@set fullmanual

@defindex id

@dircategory Stealth Software Technologies
@direntry
* SST: (sst).                   SST.
@end direntry

@ifplaintext
@chapheading SST@tie{}@w{@value{PACKAGEVERSION}} Manual
@end ifplaintext

@titlepage
@title SST@tie{}@w{@value{PACKAGEVERSION}} Manual
@subtitle @w{@value{PACKAGEDATE}}
@author Stealth Software Technologies, Inc.@:
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@include bothcontents.texi

@ifnottex
@node Top
@top SST@tie{}@w{@value{PACKAGEVERSION}} Manual

This manual is for
SST@tie{}@w{@value{PACKAGEVERSION}},
which was released
on@tie{}@w{@value{PACKAGEDATE}}@.
@ifplaintext

@insertcopying
@end ifplaintext

@menu
* Copyright Information::
* Introduction::
* Building and Installation::
* Bit Values::
* Boolean Values::
* Status Codes::
* Pointer Aliasing::
* Bit Operations::
* Concurrency Primitives::
* OpenSSL Tools::
* Release Notes::
* Concept Index::
* Identifier Index::
@end menu
@end ifnottex

@include sst/Copyright-Information.texi

@include sst/Introduction.texi

@include sst/Building-and-Installation.texi

@include sst/Bit-Values.texi

@include sst/Boolean-Values.texi

@include sst/Status-Codes.texi

@include sst/Pointer-Aliasing.texi

@include sst/Bit-Operations.texi

@include sst/Concurrency-Primitives.texi

@include sst/OpenSSL-Tools.texi

@include sst/Release-Notes.texi

@node Concept Index
@unnumbered Concept Index

@printindex cp

@node Identifier Index
@unnumbered Identifier Index

@printindex id
@bye
