/*
 * Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice (including
 * the next paragraph) shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef SST_CATALOG_SST_EXPAND_REPEATEDLY_H
#define SST_CATALOG_SST_EXPAND_REPEATEDLY_H

/* clang-format off */

#define SST_EXPAND_REPEATEDLY_0(...) __VA_ARGS__
#define SST_EXPAND_REPEATEDLY_1(...) __VA_ARGS__
#define SST_EXPAND_REPEATEDLY_2(...) __VA_ARGS__
#define SST_EXPAND_REPEATEDLY_3(...) __VA_ARGS__
#define SST_EXPAND_REPEATEDLY_4(...) SST_EXPAND_REPEATEDLY_3(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_5(...) SST_EXPAND_REPEATEDLY_4(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_6(...) SST_EXPAND_REPEATEDLY_5(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_7(...) SST_EXPAND_REPEATEDLY_6(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_8(...) SST_EXPAND_REPEATEDLY_7(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_9(...) SST_EXPAND_REPEATEDLY_8(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_10(...) SST_EXPAND_REPEATEDLY_9(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_11(...) SST_EXPAND_REPEATEDLY_10(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_12(...) SST_EXPAND_REPEATEDLY_11(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_13(...) SST_EXPAND_REPEATEDLY_12(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_14(...) SST_EXPAND_REPEATEDLY_13(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_15(...) SST_EXPAND_REPEATEDLY_14(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_16(...) SST_EXPAND_REPEATEDLY_15(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_17(...) SST_EXPAND_REPEATEDLY_16(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_18(...) SST_EXPAND_REPEATEDLY_17(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_19(...) SST_EXPAND_REPEATEDLY_18(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_20(...) SST_EXPAND_REPEATEDLY_19(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_21(...) SST_EXPAND_REPEATEDLY_20(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_22(...) SST_EXPAND_REPEATEDLY_21(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_23(...) SST_EXPAND_REPEATEDLY_22(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_24(...) SST_EXPAND_REPEATEDLY_23(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_25(...) SST_EXPAND_REPEATEDLY_24(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_26(...) SST_EXPAND_REPEATEDLY_25(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_27(...) SST_EXPAND_REPEATEDLY_26(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_28(...) SST_EXPAND_REPEATEDLY_27(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_29(...) SST_EXPAND_REPEATEDLY_28(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_30(...) SST_EXPAND_REPEATEDLY_29(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_31(...) SST_EXPAND_REPEATEDLY_30(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_32(...) SST_EXPAND_REPEATEDLY_31(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_33(...) SST_EXPAND_REPEATEDLY_32(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_34(...) SST_EXPAND_REPEATEDLY_33(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_35(...) SST_EXPAND_REPEATEDLY_34(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_36(...) SST_EXPAND_REPEATEDLY_35(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_37(...) SST_EXPAND_REPEATEDLY_36(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_38(...) SST_EXPAND_REPEATEDLY_37(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_39(...) SST_EXPAND_REPEATEDLY_38(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_40(...) SST_EXPAND_REPEATEDLY_39(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_41(...) SST_EXPAND_REPEATEDLY_40(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_42(...) SST_EXPAND_REPEATEDLY_41(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_43(...) SST_EXPAND_REPEATEDLY_42(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_44(...) SST_EXPAND_REPEATEDLY_43(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_45(...) SST_EXPAND_REPEATEDLY_44(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_46(...) SST_EXPAND_REPEATEDLY_45(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_47(...) SST_EXPAND_REPEATEDLY_46(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_48(...) SST_EXPAND_REPEATEDLY_47(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_49(...) SST_EXPAND_REPEATEDLY_48(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_50(...) SST_EXPAND_REPEATEDLY_49(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_51(...) SST_EXPAND_REPEATEDLY_50(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_52(...) SST_EXPAND_REPEATEDLY_51(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_53(...) SST_EXPAND_REPEATEDLY_52(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_54(...) SST_EXPAND_REPEATEDLY_53(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_55(...) SST_EXPAND_REPEATEDLY_54(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_56(...) SST_EXPAND_REPEATEDLY_55(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_57(...) SST_EXPAND_REPEATEDLY_56(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_58(...) SST_EXPAND_REPEATEDLY_57(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_59(...) SST_EXPAND_REPEATEDLY_58(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_60(...) SST_EXPAND_REPEATEDLY_59(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_61(...) SST_EXPAND_REPEATEDLY_60(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_62(...) SST_EXPAND_REPEATEDLY_61(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_63(...) SST_EXPAND_REPEATEDLY_62(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_64(...) SST_EXPAND_REPEATEDLY_63(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_65(...) SST_EXPAND_REPEATEDLY_64(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_66(...) SST_EXPAND_REPEATEDLY_65(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_67(...) SST_EXPAND_REPEATEDLY_66(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_68(...) SST_EXPAND_REPEATEDLY_67(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_69(...) SST_EXPAND_REPEATEDLY_68(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_70(...) SST_EXPAND_REPEATEDLY_69(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_71(...) SST_EXPAND_REPEATEDLY_70(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_72(...) SST_EXPAND_REPEATEDLY_71(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_73(...) SST_EXPAND_REPEATEDLY_72(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_74(...) SST_EXPAND_REPEATEDLY_73(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_75(...) SST_EXPAND_REPEATEDLY_74(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_76(...) SST_EXPAND_REPEATEDLY_75(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_77(...) SST_EXPAND_REPEATEDLY_76(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_78(...) SST_EXPAND_REPEATEDLY_77(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_79(...) SST_EXPAND_REPEATEDLY_78(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_80(...) SST_EXPAND_REPEATEDLY_79(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_81(...) SST_EXPAND_REPEATEDLY_80(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_82(...) SST_EXPAND_REPEATEDLY_81(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_83(...) SST_EXPAND_REPEATEDLY_82(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_84(...) SST_EXPAND_REPEATEDLY_83(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_85(...) SST_EXPAND_REPEATEDLY_84(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_86(...) SST_EXPAND_REPEATEDLY_85(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_87(...) SST_EXPAND_REPEATEDLY_86(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_88(...) SST_EXPAND_REPEATEDLY_87(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_89(...) SST_EXPAND_REPEATEDLY_88(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_90(...) SST_EXPAND_REPEATEDLY_89(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_91(...) SST_EXPAND_REPEATEDLY_90(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_92(...) SST_EXPAND_REPEATEDLY_91(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_93(...) SST_EXPAND_REPEATEDLY_92(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_94(...) SST_EXPAND_REPEATEDLY_93(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_95(...) SST_EXPAND_REPEATEDLY_94(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_96(...) SST_EXPAND_REPEATEDLY_95(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_97(...) SST_EXPAND_REPEATEDLY_96(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_98(...) SST_EXPAND_REPEATEDLY_97(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_99(...) SST_EXPAND_REPEATEDLY_98(__VA_ARGS__)
#define SST_EXPAND_REPEATEDLY_100(...) SST_EXPAND_REPEATEDLY_99(__VA_ARGS__)

/* clang-format on */

#define SST_EXPAND_REPEATEDLY_HELPER(N, ...)                           \
  SST_EXPAND_REPEATEDLY_##N(__VA_ARGS__)

#define SST_EXPAND_REPEATEDLY(N, ...)                                  \
  SST_EXPAND_REPEATEDLY_HELPER(N, __VA_ARGS__)

#endif // SST_CATALOG_SST_EXPAND_REPEATEDLY_H
