@ifxml
@ifnotxml
@c
@c For the copyright information for this file, please search up the
@c directory tree for the first COPYING file.
@c
@end ifnotxml
@end ifxml
@node Basic OpenSSL Initialization
@chapter Basic OpenSSL Initialization

@example
sst_status@w{ }sst_init_crypto(
@w{ }@w{ }void
);
@end example

@example
sst_status@w{ }sst_dnit_crypto(
@w{ }@w{ }void
);
@end example

@example
sst_status@w{ }sst_init_crypto_and_ssl(
@w{ }@w{ }void
);
@end example

@example
sst_status@w{ }sst_dnit_crypto_and_ssl(
@w{ }@w{ }void
);
@end example
