@ifxml
@ifnotxml
@c
@c For the copyright information for this file, please search up the
@c directory tree for the first COPYING file.
@c
@end ifnotxml
@end ifxml
@ifset fullmanual
@node Introduction
@chapter Introduction
@end ifset
@ifclear fullmanual
@unnumbered Introduction
@end ifclear

@noindent
SST is a software package that provides basic utilities for other
software packages developed by Stealth Software Technologies, Inc@.
