@ifxml
@ifnotxml
@c
@c For the copyright information for this file, please search up the
@c directory tree for the first COPYING file.
@c
@end ifnotxml
@end ifxml
@node Mutexes
@chapter Mutexes

@example
sst_status@w{ }sst_mutex_attr_create(
@w{ }@w{ }struct@w{ }sst_mutex_attr@w{ }*@w{ }*@w{ }attr
);
@end example

@example
sst_status@w{ }sst_mutex_attr_destroy(
@w{ }@w{ }struct@w{ }sst_mutex_attr@w{ }*@w{ }attr
);
@end example

@example
sst_status@w{ }sst_mutex_create(
@w{ }@w{ }struct@w{ }sst_mutex@w{ }*@w{ }*@w{ }mtx,
@w{ }@w{ }struct@w{ }sst_mutex_attr@w{ }*@w{ }attr
);
@end example

@example
sst_status@w{ }sst_mutex_destroy(
@w{ }@w{ }struct@w{ }sst_mutex@w{ }*@w{ }mtx
);
@end example

@example
sst_status@w{ }sst_mutex_lock(
@w{ }@w{ }struct@w{ }sst_mutex@w{ }*@w{ }mtx
);
@end example

@example
sst_status@w{ }sst_mutex_unlock(
@w{ }@w{ }struct@w{ }sst_mutex@w{ }*@w{ }mtx
);
@end example
