@ifxml
@ifnotxml
@c
@c For the copyright information for this file, please search up the
@c directory tree for the first COPYING file.
@c
@end ifnotxml
@end ifxml
@node Status Codes
@chapter Status Codes

@noindent
SST provides a set of status codes that can be used for function return
values@.

@menu
* Status Code Names and Values::
* Status Code Meanings::
* Custom Status Codes::
* Using Status Codes in Strings::
* Status Code Reference::
@end menu

@lowersections
@include sst/Status-Code-Names-and-Values.texi

@include sst/Status-Code-Meanings.texi

@include sst/Custom-Status-Codes.texi

@include sst/Using-Status-Codes-in-Strings.texi

@include sst/Status-Code-Reference.texi
@raisesections
