@ifxml
@ifnotxml
@c
@c For the copyright information for this file, please search up the
@c directory tree for the first COPYING file.
@c
@end ifnotxml
@end ifxml
@node Status Code Names and Values
@chapter Status Code Names and Values

@idindex @w{@t{SST_STATUS_MAXVAL}}
@idindex @w{@t{SST_STATUS_MAXVAL_MAXVAL}}
@idindex @w{@t{sst_status}}
@noindent
Each status code has a name and a value@.
Each name is at most 63 characters long and is defined as a macro that
expands to a decimal integer constant with a
@w{@t{UL}}
suffix and the corresponding value@.
There are
@tex
$n$
@end tex
@ifnottex
@w{@i{n}}
@end ifnottex
status codes in total, where
@tex
$1 \le n \le 2^{31}$,
@end tex
@ifnottex
@w{1 @lequ{} @i{n} @lequ{} 2@sps{,31,}},
@end ifnottex
and their values are 0
@tex
to~$n - 1$.
@end tex
@ifnottex
to@tie{}@w{@i{n} @msign{} 1}@.
@end ifnottex
The values are conventionally held with the
@w{@t{sst_status}}
type, which is a synonym for the
@w{@t{unsigned long int}}
type@.
The
@w{@t{SST_STATUS_MAXVAL}}
macro expands to a decimal integer constant with a
@w{@t{UL}}
suffix and value
@tex
$n - 1$,
@end tex
@ifnottex
@w{@i{n} @msign{} 1},
@end ifnottex
and the
@w{@t{SST_STATUS_MAXVAL_MAXVAL}}
macro expands to a decimal integer constant with a
@w{@t{UL}}
suffix and value
@tex
$2^{31} - 1$.
@end tex
@ifnottex
@w{2@sps{,31,} @msign{} 1}@.
@end ifnottex

@idindex @w{@t{sst_status_name}}
@include indent.texi
The following function maps the value of a status code to the name of
the status code:

@example
char const * sst_status_name(
  sst_status s
);
@end example

@noindent
If
@w{@t{s}}
is larger than
@w{@t{SST_STATUS_MAXVAL}},
then the function restarts and behaves as if
@w{@t{s}}
were
@w{@t{SST_UNKNOWN}}@.
Otherwise, the function returns a pointer to a string with static
storage duration that holds the name of the status code@.
If the program attempts to modify the string, then the behavior is
undefined@.

@idindex @w{@t{sst_status_value}}
@include indent.texi
The following function maps the name of a status code to the value of
the status code:

@example
sst_status sst_status_value(
  char const * s
);
@end example

@noindent
If
@w{@t{s}}
is a null pointer, then the function returns
@w{@t{SST_UNKNOWN}}@.
Otherwise, if
@w{@t{s}}
does not point to a string, then the behavior is undefined@.
Otherwise, if the string does not hold the name of a status code, then
the function returns
@w{@t{SST_UNKNOWN}}@.
Otherwise, the function returns the value of the status code@.
