//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

ifeval::[{bl_minimum_bash_version_value} < 4002]

[#bl-global-variable-declarations]
= Global variable declarations

Bash <4.2 does not support `declare -g` in functions.
Ignoring shadowing problems, global variable declarations can always be
safely omitted except when a function needs to use a global associative
array that may not have been declared yet.
In this case, instead of writing `declare -g -A foo` in the function,
write `declare -A foo` in the global scope just before the function.

For stylistic reasons, you may want to put commented-out
`# Bash >=4.2: declare -g` declarations in a function for all global
variables used by the function regardless of whether the declarations
would technically be necessary.
These declarations are helpful to the reader, and you can enable them
later if you eventually migrate to Bash >=4.2.

[WARNING]
====
If you're working on the SST Bash library itself, do not put any global
variable declarations at the top of any function file.
Although that area looks like it's the global scope, it actually isn't,
as the library's automatic function loading mechanism loads function
files in function scope.
Instead, add a commented-out `# Bash >=4.2: declare -g` declaration to
the function, and, if you're declaring a global associative array, also
add a declaration to the "Global associative array declarations" section
in the prelude.
====

endif::[]

//
