//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#bl-including-the-library]
= Including the library

. {empty}
+
[source,sh,subs="{sst_subs_source}"]
----
#! /bin/sh -
set -e || exit $?
. sst.bash
----

. {empty}
+
[source,sh,subs="{sst_subs_source}"]
----
#! /bin/sh -
set -e || exit $?
if test -f sst.bash; then
  . ./sst.bash
else
  . sst.bash
fi
----

. {empty}
+
[source,sh,subs="{sst_subs_source}"]
----
pass:[#! /bin/sh -]
pass:[case $0 in /*)]
pass:[  x=$0]
pass:[;; *)]
pass:[  x=./$0]
pass:[esac]
pass:[r='\(.*/\)']
pass:[x=`expr "x$x" : "x$r"`. || exit $?]
pass:[set -e || exit $?]
pass:[. "$x/sst/sst.bash"]
----

For repository scripts:

[source,sh,subs="{sst_subs_source}"]
----
pass:[#-----------------------------------------------------------------------]
pass:[# Include the SST Bash library]
pass:[#-----------------------------------------------------------------------]
pass:[#]
pass:[# Include the first sst.bash file found by searching up the directory]
pass:[# tree starting from the location of this script file. If no such file]
pass:[# is found, fall back to including plain sst.bash with PATH resolution.]
pass:[#]
pass:[# This section is written in portable shell to ensure it works properly]
pass:[# in any shell.]
pass:[#]
pass:[]
pass:[case ${SST_SEARCH_UP_X-} in '')]
pass:[  case $0 in /*)]
pass:[    SST_SEARCH_UP_X=$0]
pass:[  ;; *)]
pass:[    SST_SEARCH_UP_X=./$0]
pass:[  esac]
pass:[  SST_SEARCH_UP_R='\<b></b>(.*/\<b></b>)']
pass:[  SST_SEARCH_UP_X=`]
pass:[    expr "x${SST_SEARCH_UP_X?}" : "x${SST_SEARCH_UP_R?}"]
pass:[  `. || exit $?]
pass:[  unset SST_SEARCH_UP_R]
pass:[  SST_SEARCH_UP_X=`]
pass:[    cd "${SST_SEARCH_UP_X?}" || exit $?]
pass:[    while :; do]
pass:[      if test -f sst.bash; then]
pass:[        case ${PWD?} in *[!/\]*)]
pass:[          printf '%s\n' "${PWD?}"/ || exit $?]
pass:[        ;; *)]
pass:[          printf '%s\n' "${PWD?}" || exit $?]
pass:[        esac]
pass:[        exit]
pass:[      fi]
pass:[      case ${PWD?} in *[!/\]*)]
pass:[        cd ..]
pass:[      ;; *)]
pass:[        exit]
pass:[      esac]
pass:[    done]
pass:[  ` || exit $?]
pass:[  export SST_SEARCH_UP_X]
pass:[esac]
pass:[set -e || exit $?]
pass:[. "${SST_SEARCH_UP_X?}"sst.bash]
pass:[unset SST_SEARCH_UP_X]
----

//
