//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#bl-including-the-library]
= Including the library

. {empty}
+
[source,sh,subs="{sst_subs_source}"]
----
#! /bin/sh -
set -e || exit $?
. sst.bash
----

. {empty}
+
[source,sh,subs="{sst_subs_source}"]
----
#! /bin/sh -
set -e || exit $?
if test -f sst.bash; then
  . ./sst.bash
else
  . sst.bash
fi
----

. {empty}
+
[source,sh,subs="{sst_subs_source}"]
----
#! /bin/sh -
case $0 in /{sst_asterisk})
  x=$0
;; {sst_asterisk})
  x=./$0
esac
r='{sst_backslash}{sst_empty_tag}(.{sst_asterisk}/{sst_backslash}{sst_empty_tag})'
x={sst_backtick}expr "x$x" : "x$r"{sst_backtick}. || exit $?
set -e || exit $?
. "$x/sst/sst.bash"
----

For repository scripts:

[source,sh,subs="{sst_subs_source}"]
----
#-----------------------------------------------------------------------
# Include the SST Bash library
#-----------------------------------------------------------------------
#
# Include the first sst.bash file found by searching up the directory
# tree starting from the location of this script file. If no such file
# is found, fall back to including plain sst.bash with PATH resolution.
#
# This section is written in portable shell to ensure it works properly
# in any shell.
#

case ${sst_lbrace}SST_SEARCH_UP_X-{sst_rbrace} in '')
  case $0 in /{sst_asterisk})
    SST_SEARCH_UP_X=$0
  ;; {sst_asterisk})
    SST_SEARCH_UP_X=./$0
  esac
  SST_SEARCH_UP_R='{sst_backslash}{sst_empty_tag}(.{sst_asterisk}/{sst_backslash}{sst_empty_tag})'
  SST_SEARCH_UP_X={sst_backtick}
    expr "x${sst_lbrace}SST_SEARCH_UP_X?{sst_rbrace}" : "x${sst_lbrace}SST_SEARCH_UP_R?{sst_rbrace}"
  {sst_backtick}. || exit $?
  unset SST_SEARCH_UP_R
  SST_SEARCH_UP_X={sst_backtick}
    cd "${sst_lbrace}SST_SEARCH_UP_X?{sst_rbrace}" || exit $?
    while :; do
      if test -f sst.bash; then
        case ${sst_lbrace}PWD?{sst_rbrace} in {sst_asterisk}[!/{sst_backslash}]{sst_asterisk})
          printf '%s{sst_backslash}n' "${sst_lbrace}PWD?{sst_rbrace}"/ || exit $?
        ;; {sst_asterisk})
          printf '%s{sst_backslash}n' "${sst_lbrace}PWD?{sst_rbrace}" || exit $?
        esac
        exit
      fi
      case ${sst_lbrace}PWD?{sst_rbrace} in {sst_asterisk}[!/{sst_backslash}]{sst_asterisk})
        cd ..
      ;; {sst_asterisk})
        exit
      esac
    done
  {sst_backtick} || exit $?
  export SST_SEARCH_UP_X
esac
set -e || exit $?
. "${sst_lbrace}SST_SEARCH_UP_X?{sst_rbrace}"sst.bash
unset SST_SEARCH_UP_X
----

//
