//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#bl-prepare-dist-repo-bash]
= The `prepare-dist-repo.bash` script

.Bash
[source,subs="{sst_subs_source}"]
----
prepare-dist-repo.bash <json>
----

The `prepare-dist-repo.bash` script makes a commit to a private
<<bs_distribution_repository>> for preview purposes before the
`<<bl_publish_dist_repo_bash>>` script is used to publish the
preview commit to a corresponding public distribution repository.

:fp_argument_name: json
include::bl_json_argument_fragment.adoc[]

The following arguments may be specified in `<json>`:

`pull_repo`::
The URL of the repository to clone and make the preview commit in.
The commit will be made on top of the commit specified by `pull_commit`.
+
The URL
include::bl_double_quoted_expansion_fragment.adoc[]
For example, a URL such as
`+https://gitlab-ci-token:${CI_JOB_TOKEN-}@gitlab.stealthsoftwareinc.com/stealth/sst.git+`
could be used to clone a repository while running in a GitLab CI job.
+
More than one URL may be specified by providing an array of strings
instead of a single string.
The array will act as a list of mirrors from which to try clone the
repository.
The mirrors are attempted to be cloned in order, stopping after the
first successful clone that contains `pull_commit`.

`pull_commit` (optional)::
The commit of `pull_repo` on top of which to make the preview commit.
By default, `pull_commit` is the default branch of `pull_repo`.

`push_repo`::
A repository URL or an array of repository URLs to which to push the
preview commit.
The preview commit will always be pushed to a new branch `preview-<x>`,
where `<x>` is derived from the source of the CI job.
This argument is optional and defaults to `pull_repo`.

`update_script` (optional)::
A path to an update script to run instead of the default update script.

`post_update_script` (optional)::
A path to a post-update script to run instead of the default post-update
script.
The default post-update script does nothing.

`commit_script` (optional)::
A path to a commit script to run instead of the default commit script.

`post_commit_script` (optional)::
A path to a post-commit script to run instead of the default post-commit
script.
The default post-commit script does nothing.

`gitbundle`::
The name of the `.gitbundle` file to produce as an artifact to use as
input to the `<<bl_publish_dist_repo_bash>>` script.
This argument is optional and defaults to `preview.gitbundle`.

`dist_archive`::
A path to an archive to use instead of the default distribution archive,
which is located using the `<<bl_sst_find_dist_archive>>` function.
This argument may also be set to "```git-archive```" to create an
ephemeral distribution archive that contains the content of `HEAD`
inside a container directory with an unspecified name.
This argument is optional.

`tag_transform`::
An optional `{ut_sed}` script to use to transform the tag name when
preparing from a tag.

//
