//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#bl-sst-csf]
= The `sst_csf` function

.Bash
[source,subs="{sst_subs_source}"]
----
include::partials/bl_include_prelude.adoc[]

sst_csf [<&var>]...
----

If no arguments are given, the `sst_csf` function copies the content of
standard input to standard output, appending an "```x```" character and
a newline character.
Otherwise, the function removes the last character from each `<&var>` if
it exists as an "```x```" character, and removes the next last character
if it exists as a newline character.

The purpose of the `sst_csf` function is to allow command substitutions
to be used that only remove a single trailing newline character instead
of as many trailing newline characters as possible.
To be more specific, instead of writing `foo=$(bar)`, you can write
`foo=$(bar | sst_csf); sst_csf foo`.

The "`csf`" abbreviation in the function name is short for "`**c**ommand
**s**ubstitution **f**ix`".

indexterm:["sst_csf form, read in"]
When input is said to be __read in `sst_csf` form__, it means that the
input is taken to be all characters up to but not including a possible
single trailing newline character.

indexterm:["sst_csf form, written in"]
When output is said to be __written in `sst_csf` form__, it means that
the output is followed by a single trailing newline character.

//
