//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#bl-sst-array-from-zterm]
= The `sst_array_from_zterm` function

.Bash
[source,subs="{sst_subs_source}"]
----
include::partials/bl_include_prelude.adoc[]

sst_array_from_zterm <array> [<command> [<arg>]pass:r[...]]
----

The `{bl_sst_array_from_zterm}` function parses a sequence of
zero-terminated elements into `<array>`.

If `<command> [<arg>]...` is given, it is run with standard input as its
standard input and the elements are parsed from its standard output.
Otherwise, the elements are parsed from standard input.

If the element sequence is empty, the resulting array will be empty.
Otherwise, the zero terminator of the last element is optional if the
last element is nonempty.

[WARNING]
====
:fp_function: `{bl_sst_array_from_zterm}`
include::bl_pipeline_subshell_fragment.adoc[]

For example, in
`{bl_printf} 'a\0' | {bl_sst_array_from_zterm} xs`,
if the `{bl_sst_array_from_zterm}` command runs in a subshell, it will
populate the `xs` array in the subshell and then exit the subshell,
leaving the `xs` array in the current shell untouched.
`{bl_sst_array_from_zterm} xs {bl_printf} 'a\0'`,
on the other hand, will always work as intended.
====

.{empty}
[example]
====
[source,subs="{sst_subs_source}"]
----
{bl_sst_array_from_zterm} xs {bl_printf} ''       # xs=()
{bl_sst_array_from_zterm} xs {bl_printf} '\0'     # xs=('')
{bl_sst_array_from_zterm} xs {bl_printf} 'a'      # xs=('a')
{bl_sst_array_from_zterm} xs {bl_printf} 'a\0'    # xs=('a')
{bl_sst_array_from_zterm} xs {bl_printf} '\0\0'   # xs=('' '')
{bl_sst_array_from_zterm} xs {bl_printf} 'a\0\0'  # xs=('a' '')
{bl_sst_array_from_zterm} xs {bl_printf} 'a\0b'   # xs=('a' 'b')
{bl_sst_array_from_zterm} xs {bl_printf} 'a\0b\0' # xs=('a' 'b')
----
====

//
