//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

The {exkb46kh_package_name} build system is built on top of the
{bs_gnu_autotools}.
Before you can start using the build system, you need to identify which
__((package format))__ of {exkb46kh_package_name} you're working with.
{exkb46kh_package_name} is generally available in three slightly
different package formats:

1. {empty}
The __((source repository))__.
This repository is only available internally within Stealth.
The other package formats are generally derived from this one.

2. [[bs_distribution_repository]]
A __((distribution repository))__.
ifdef::exkb46kh_public_distribution_repository_url[]
The primary public distribution repository for {exkb46kh_package_name}
is available at link:{exkb46kh_public_distribution_repository_url}[,window=_blank].
You may also have access to other distribution repositories that Stealth
has created for private distribution purposes.
endif::[]
ifndef::exkb46kh_public_distribution_repository_url[]
There is no public distribution repository for {exkb46kh_package_name}.
However, you may have access to other distribution repositories that
Stealth has created for private distribution purposes.
endif::[]

3. {empty}
A __((distribution archive))__.

To identify which package format you're working with, use the following
algorithm:

1. {empty}
If you started with an archive file like
`{exkb46kh_package_tarname}-<version>.tar.gz` and it extracts to a
directory that includes a file named `Makefile.in`, then you're working
with a distribution archive.
+
[IMPORTANT]
====
If the extracted directory does not include a file named `Makefile.in`,
then you may have mistakenly downloaded a __((source archive))__.
This is what you will typically get if you use a download button when
viewing the source repository in a repository manager like GitHub or
GitLab.
{exkb46kh_package_name} does not support being built from a source
archive.

Note that this only applies to download buttons for the source
repository, not for a distribution repository.
Using a download button on a distribution repository will generally
yield a valid distribution archive.
====

2. Otherwise, if the version control repository includes a file named
`Makefile.in` in the root directory, then you're working with a
distribution repository.

3. Otherwise, you're working with the source repository.

Once you know which package format you're working with, using the build
system consists of three main steps:

1. _Initializing_ the build system.
((("build system, initializing")))
2. _Configuring_ the build system.
((("build system, configuring")))
3. _Running_ the build system.
((("build system, running")))

If you're working with the source repository, you need to perform steps
1, 2, and 3.
Otherwise, you only need to perform steps 2 and 3.
Step 1 is only designed to work on modern Linux systems with a variety
of tools installed, but steps 2 and 3 are designed to work on a variety
of Unix-like systems with minimal tools installed.
The idea is that developers work with the source repository and produce
distribution archives and distribution repositories for general use.

//
