//
// For the copyright information for this file, please search up the
// directory tree for the first COPYING file.
//
[[cl_nlohmann_json_tools]]
= `nlohmann::json` tools

The following function is provided for parsing JSON entities into
arbitrary types:

.{cpp}
[source,cpp]
----
#include <sst/json/get_to.h>
namespace sst::json {

template<class ValueType, class BasicJsonType, int = 0>
ValueType & get_to(BasicJsonType const & src, ValueType & dst) { ... }

}
----

If `ValueType` is
an integer type (as defined by `std::is_integral`) or
`BIGNUM` (if `-lcrypto` is available),
then the internal type of `src` must be `integer_t`, `unsigned_t`,
`boolean_t`, or `string_t`.
For `integer_t` and `unsigned_t`, the parsed value is simply the
internal value.
For `boolean_t`, the parsed values of true and false are 1 and 0,
respectively.
For `string_t`, the accepted syntax and parsed value is defined by the
following grammar, which is inspired by {cpp}`'s grammar for integer
literals:

====
_value_: +
{gindent} _sign_~_opt_~ _magnitude_ +
{gindent} _boolean_

_sign_: one of +
{gindent} `+` `-`

_magnitude_: +
{gindent} _binary-magnitude_ +
{gindent} _octal-magnitude_ +
{gindent} _decimal-magnitude_ +
{gindent} _hexadecimal-magnitude_

_binary-magnitude_: +
{gindent} `0b` _binary-digit_ +
{gindent} `0B` _binary-digit_ +
{gindent} _binary-magnitude_ `'`~_opt_~ _binary-digit_

_octal-magnitude_: +
{gindent} `0` +
{gindent} _octal-magnitude_ `'`~_opt_~ _octal-digit_

_decimal-magnitude_: +
{gindent} _nonzero-decimal-digit_ +
{gindent} _decimal-magnitude_ `'`~_opt_~ _decimal-digit_

_hexadecimal-magnitude_: +
{gindent} `0x` _hexadecimal-digit_ +
{gindent} `0X` _hexadecimal-digit_ +
{gindent} _hexadecimal-magnitude_ `'`~_opt_~ _hexadecimal-digit_

_binary-digit_: one of +
{gindent} `0` `1`

_octal-digit_: one of +
{gindent} `0` `1` `2` `3` `4` `5` `6` `7`

_nonzero-decimal-digit_: one of +
{gindent} `1` `2` `3` `4` `5` `6` `7` `8` `9`

_decimal-digit_: one of +
{gindent} `0` `1` `2` `3` `4` `5` `6` `7` `8` `9`

_hexadecimal-digit_: one of +
{gindent} `0` `1` `2` `3` `4` `5` `6` `7` `8` `9` +
{gindent} `a` `b` `c` `d` `e` `f` +
{gindent} `A` `B` `C` `D` `E` `F`

_boolean_: one of +
{gindent} `true` `false`
====

If `ValueType` is a ``std::vector``-like type, then the internal type of
`src` must be `array_t`.
`dst` will first be cleared, and then each element of the array will be
appended to `dst` after being parsed by calling `sst::json::get_to`
recursively.

If `ValueType` is a ``std::map``-like type, then the internal type of
`src` must be `object_t`.
`dst` will first be cleared, and then each member of the object will be
inserted into `dst` after being parsed by calling `sst::json::get_to`
recursively.

If `ValueType` is any other type, then the parsing will be forwarded to
``nlohmann::json``{blank}`'s built-in parsing logic by calling
`src.get_to(dst)`.
In particular, this means that ``nlohmann::json``{blank}`'s arbitrary
type parsing feature (i.e., user-provided `from_json` functions) will
work when calling `sst::json::get_to`.

Except perhaps when parsing is forwarded to ``nlohmann::json``{blank}`'s
built-in parsing logic, this function will reliably throw an exception
if any kind of error occurs.
In particular, it will throw an exception if `ValueType` is an integer
type that cannot represent a parsed integer value.

The following functions are provided for parsing JSON object members:

.{cpp}
[source,cpp]
----
#include <sst/json/get_to.h>
namespace sst::json {

// (1)
template<class ValueType, class BasicJsonType>
ValueType & get_to(BasicJsonType const & src,
    typename BasicJsonType::object_t::key_type const & key,
    ValueType & dst) { ... }

// (2)
template<class ValueType, class BasicJsonType>
ValueType & get_to(BasicJsonType const & src,
    typename BasicJsonType::object_t::key_type const & key,
    ValueType & dst, ValueType const & default_value) { ... }

}
----

The internal type of `src` must be `object_t`.
For (1), `src` must contain a member named `key`, whose value will be
parsed by calling `sst::json::get_to` recursively.
For (2), the behavior is the same as (1) except that if `src` does not
contain a member named `key`, then `dst` will be set to `default_value`.

The following functions are provided for convenience.
They are equivalent to the corresponding `sst::json::get_to` functions
except they return their results by value instead of having `dst`
parameters:

.{cpp}
[source,cpp]
----
#include <sst/json/get_to.h>
namespace sst::json {

template<class ValueType, class BasicJsonType>
ValueType get_as(BasicJsonType const & src) { ... }

template<class ValueType, class BasicJsonType>
ValueType get_as(BasicJsonType const & src,
    typename BasicJsonType::object_t::key_type const & key) { ... }

template<class ValueType, class BasicJsonType>
ValueType get_as(BasicJsonType const & src,
    typename BasicJsonType::object_t::key_type const & key,
    ValueType const & default_value) { ... }

}
----
