//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#cl-sst-preinit]
= The `sst::preinit` class

.{cpp}
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/preinit.hpp[sst/catalog/preinit.hpp,window=_blank]>
namespace sst {

struct xref:{cl_sst_preinit_url}[preinit] {

  template<class... Ts>
  preinit(Ts &&...) {
  }

};

}
----

The `{cl_sst_preinit}` class accepts any arguments in its constructor
and does nothing.
This is primarily useful for running code at the beginning of a
{cl_member_initializer_list}.

.{empty}
[example]
====
.`sst-example-{example-number}.cpp`
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/SST_ASSERT.h[sst/catalog/SST_ASSERT.h,window=_blank]>
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/preinit.hpp[sst/catalog/preinit.hpp,window=_blank]>

class foo {
  {cl_sst_preinit} preinit{sst_underscore};
  int x{sst_underscore};
public:
  foo(int const x) : preinit{sst_underscore}++((++{cl_SST_ASSERT_cpp_1}++((++x {sst_gt} 0)), 0)), x{sst_underscore}(x) {
  }
};

int main() {
  foo f(0);
  return 0;
}
----

include::partials/cl_cpp_compilation_command.adoc[]

.Possible output
[source,subs="{sst_subs_source}"]
----
terminate called after throwing an instance of '{cl_std_logic_error}'
  what():  sst-example-{example-number}.cpp:8: Assertion failed: (x > 0)
Aborted (core dumped)
----
====

//
