//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#cl-sst-set-bit]
= The `sst::set_bit` function

.{cpp}
[source,cpp]
----
#include <sst/bit.h>
namespace sst {

// (1)
template<class X, class Q, class R>
constexpr X set_bit(X x, Q q, R r, bool b) noexcept;

// (2)
template<class X, class R>
constexpr X set_bit(X x, R r, bool b) noexcept;

// (3)
template<class Q, class R>
void * set_bit(void * x, Q q, R r, bool b) noexcept;

// (4)
template<class R>
void * set_bit(void * x, R r, bool b) noexcept;

}
----

The `sst::set_bit` function sets the bit at index
stem:[\mathtt{q} \cdot \mathtt{CHAR\_BIT} + \mathtt{r}]
of the two`'s complement representation of `x` +(for (1) and (2))+ or
the region of bytes pointed to by `x` +(for (3) and (4))+ to `b`.
For (1) and (2), the bits of `x` are zero indexed starting with the
least significant bit (and the most significant bit is the sign bit if
`X` is signed), and the function returns the resulting value.
For (3) and (4), the bits of the region of bytes pointed to by `x` are
zero indexed starting with the least significant bit of the first byte,
and the function returns `x`.

`X`, `Q`, and `R` may be any {ce_std_is_integral_url}[integer types].
If `x` is a null pointer, `q` is negative, `r` is negative, or
stem:[\mathtt{q} \cdot \mathtt{CHAR\_BIT} + \mathtt{r}]
is greater than or equal to the number of nonpadding bits in `X` or the
number of bits in the region of bytes pointed to by `x`, the behavior is
undefined.
For (2) and (4), `q` is omitted and taken to be zero.

Prior to {cpp}20, signed integers are permitted to use ones`' complement
or sign-magnitude representation instead of two`'s complement.
This does not affect the behavior of (1) or (2), except that if the
resulting value cannot be represented by `X` (i.e., if `X` is signed,
`x` is zero, and the most significant bit is being set to 1), the
behavior is undefined.

//
