//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#cl-sst-str-cmp]
= The `sst::str_cmp` function

.{cpp}
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/str_cmp.hpp[sst/catalog/str_cmp.hpp,window=_blank]>
namespace sst {

template<class IteratorA,
         class IteratorB,
         class ValueType =
             typename {cl_std_iterator_traits}<IteratorA>::{cl_std_iterator_traits_value_type}>
constexpr int str_cmp(IteratorA a,
                      IteratorB b,
                      ValueType const & null_terminator = ValueType());

}
----

The `{cl_sst_str_cmp}` function compares the two null-terminated
sequences `a` and `b` and returns a value less than, equal to, or
greater than zero if `a` is less than, equal to, or greater than `b`,
respectively.

.{empty}
[example]
====
.`a.cpp`
[source,cpp,subs="{sst_subs_source}"]
----
#include <iostream>
#include <vector>

#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/str_cmp.hpp[sst/catalog/str_cmp.hpp,window=_blank]>

int main() {
  {cl_std_cout} << {cl_sst_str_cmp}("foo", "foo") << "\n";
  {cl_std_cout} << {cl_sst_str_cmp}("foo", "Foo") << "\n";
  {cl_std_cout} << {cl_sst_str_cmp}(L"Foo", L"foo") << "\n";
  {cl_std_vector}<int> x{1, 2, 3, 4, 5, 6};
  {cl_std_vector}<int> y{1, 2, 3, 6, 5};
  {cl_std_cout} << {cl_sst_str_cmp}(x.{cl_std_vector_begin}(), y.{cl_std_vector_begin}(), 3) << "\n";
  {cl_std_cout} << {cl_sst_str_cmp}(x.{cl_std_vector_begin}(), y.{cl_std_vector_begin}(), 5) << "\n";
  {cl_std_cout} << {cl_sst_str_cmp}(x.{cl_std_vector_begin}(), y.{cl_std_vector_begin}(), 6) << "\n";
}
----

[listing,subs="{sst_subs_source}"]
----
$ g++ a.cpp -lsst

$ ./a.out
0
1
-1
0
-1
1
----
====

//
