//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#cl-sst-boxed]
= The `sst::boxed` class template

The `sst::boxed` class template describes a class that stores a value of
type `T` as a distinct type identified by type `Tag` in addition to type
`T`, allowing different kinds of values of type `T` to be distinguished
from each other.

.{cpp}
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/boxed.hpp[sst/catalog/boxed.hpp,window=_blank]>
namespace sst {

template<class T, class Tag>
class boxed {
public:

  using value_type = T;

  // Construction is forwarded to T.
  template<class... Args> explicit constexpr boxed(Args &&... args);

  // Copy construction, copy assignment, move construction, move
  // assignment, and destruction are intentionally implicit.

  // Value retrieval
  explicit {cl_SST_CPP14_CONSTEXPR} operator T &() noexcept;
  explicit constexpr operator T const &() const noexcept;
  {cl_SST_CPP14_CONSTEXPR} T & value() noexcept;
  constexpr T const & value() const noexcept;

  // Comparisons for aliases and publicly derived classes
  constexpr bool operator<(boxed const & b) const
      noexcept(noexcept({cl_std_declval}<T>() < {cl_std_declval}<T>()));
  constexpr bool operator>(boxed const & b) const
      noexcept(noexcept({cl_std_declval}<T>() > {cl_std_declval}<T>()));
  constexpr bool operator<=(boxed const & b) const
      noexcept(noexcept({cl_std_declval}<T>() <= {cl_std_declval}<T>()));
  constexpr bool operator>=(boxed const & b) const
      noexcept(noexcept({cl_std_declval}<T>() >= {cl_std_declval}<T>()));
  constexpr bool operator==(boxed const & b) const
      noexcept(noexcept({cl_std_declval}<T>() == {cl_std_declval}<T>()));
  constexpr bool operator!=(boxed const & b) const
      noexcept(noexcept({cl_std_declval}<T>() != {cl_std_declval}<T>()));

  // Comparisons for privately derived classes
  constexpr bool operator<(Tag const & b) const
      noexcept(noexcept({cl_std_declval}<T>() < {cl_std_declval}<T>()));
  constexpr bool operator>(Tag const & b) const
      noexcept(noexcept({cl_std_declval}<T>() > {cl_std_declval}<T>()));
  constexpr bool operator<=(Tag const & b) const
      noexcept(noexcept({cl_std_declval}<T>() <= {cl_std_declval}<T>()));
  constexpr bool operator>=(Tag const & b) const
      noexcept(noexcept({cl_std_declval}<T>() >= {cl_std_declval}<T>()));
  constexpr bool operator==(Tag const & b) const
      noexcept(noexcept({cl_std_declval}<T>() == {cl_std_declval}<T>()));
  constexpr bool operator!=(Tag const & b) const
      noexcept(noexcept({cl_std_declval}<T>() != {cl_std_declval}<T>()));

};

}
----

//
