//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#cl-sst-openssl-rand-bytes-rng]
= The `sst::openssl_rand_bytes_rng` class

.{cpp}
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/openssl_rand_bytes_rng.hpp[sst/catalog/openssl_rand_bytes_rng.hpp,window=_blank]>
namespace sst {

#if {cl_SST_WITH_OPENSSL_CRYPTO}

class openssl_rand_bytes_rng final {
public:

  using result_type = unsigned char;

  static constexpr unsigned char min() noexcept {
    return 0;
  }

  static constexpr unsigned char max() noexcept {
    return {cl_sst_type_max}<unsigned char>::value;
  }

  template<{cl_std_integral} Size>
  explicit openssl_rand_bytes_rng(Size n);

  openssl_rand_bytes_rng();

  openssl_rand_bytes_rng(openssl_rand_bytes_rng &&) noexcept;

  openssl_rand_bytes_rng(openssl_rand_bytes_rng const &) = delete;
  openssl_rand_bytes_rng & operator=(openssl_rand_bytes_rng const &) = delete;
  openssl_rand_bytes_rng & operator=(openssl_rand_bytes_rng &&) = delete;

  ~openssl_rand_bytes_rng() noexcept;

  void refill(bool eager = true);

  unsigned char operator()();

  template<class OutputIt, {cl_std_integral} Size>
  OutputIt operator()(OutputIt dst, Size n);

};

#endif

}
----

//
