//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#cl-sst-errno-exception]
= The `sst::errno_exception` class

.{cpp}
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/errno_exception.hpp[sst/catalog/errno_exception.hpp,window=_blank]>
namespace sst {

class link:{cl_sst_errno_exception_url}[errno_exception,window=_blank] : public {cl_std_runtime_error} {
public:

  explicit errno_exception({cl_std_string} const & message, int code);
  explicit errno_exception(char const * message, int code);
  explicit errno_exception({cl_std_string} const & message);
  explicit errno_exception(char const * message);
  explicit errno_exception(int code);
  explicit errno_exception();

  int code() const noexcept;

};

}
----

. {empty}
If `message` is a null pointer, the behavior is undefined.

. {empty}
Otherwise, if `message` is empty, it will be adjusted to
`{cl_sst_errno_error_string}(code) + "."`.

. {empty}
Otherwise, if `message` ends with `()`, it will be adjusted to
`message + " failed: " + {cl_sst_errno_error_string}(code) + "."`.

. {empty}
Otherwise, `message` will be adjusted to
`message + ": " + {cl_sst_errno_error_string}(code) + "."`.

Omitting `code` is equivalent to passing `{cl_errno}`.

//
