//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#{cl_unique_pass_algorithms_id}]
= {cl_unique_pass_algorithms_title}

An algorithm with an iterator parameter `p` is called __unique-pass__
with respect to `p` if the algorithm satisfies all of the following
properties:
((("unique-pass algorithm")))

. {empty}
For any two arithmetic operations stem:[A] and stem:[B] performed on two
iterators derived from `p` (i.e., any of `pass:[++q]`, `pass:[q++]`,
`--q`, `q--`, `q+n`, `n+q`, `q+=n`, `q-n`, or `q-=n` where `q` is
derived from `p`), either stem:[A] is {cl_sequenced_before} stem:[B] or
stem:[B] is {cl_sequenced_before} stem:[A].
In other words, all arithmetic operations on iterators derived from `p`
are separated by {cl_sequence_points}.

. {empty}
Each time an arithmetic operation stem:[A] is performed on an iterator
derived from `p`, the next arithmetic operation is performed on the
result of stem:[A] or a copy of the result, even if stem:[A] is trivial
(e.g., `q+0`).
This induces a unique chain of iterators derived from `p` that begins
with `p` itself, where each successive iterator is the result of the
next arithmetic operation on (a copy of) the previous iterator.

. {empty}
For any two dereference operations stem:[A] and stem:[B] performed on
(copies of) two iterators in the chain, either stem:[A] is
{cl_sequenced_before} stem:[B] or stem:[B] is {cl_sequenced_before}
stem:[A].
In other words, all dereferences of (copies of) two iterators in the
chain are separated by {cl_sequence_points}.

. {empty}
Each time an iterator derived from `p` is dereferenced, the iterator is
either the newest iterator or the second newest iterator in the chain.
Furthermore, if it is the second newest iterator, then the newest
iterator has not yet been dereferenced.
This permits `pass:[*p++]` and `*p--` but forbids sequences such as
`pass:[q=p++],*p,*q`.

//
