//
// Copyright (C) 2012-2024 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

.{cpp}
[source,cpp,subs="{sst_subs_source}"]
----
#include <link:{repo_browser_url}/src/c-cpp/include/sst/catalog/{f}.hpp[sst/catalog/{f}.hpp,window=_blank]>
// or:   <sst/integer.h>
namespace sst {

template<class IntType1, class IntType2>
constexpr bool {f}(IntType1 a, IntType2 b) noexcept;

}
----

The `sst::{f}` function determines whether `a` is {r} `b` for any two
nonnegative values `a` and `b` of any two {cr_integer_types} `IntType1`
and `IntType2` without generating any compiler warnings.

[subs="-replacements"]
The {cr_usual_arithmetic_conversions_cpp} guarantee that comparing `a`
to `b` with the plain `{o}` operator always yields the expected result
if `a` and `b` are nonnegative, but it is common for compilers to
generate warnings when `IntType1` and `IntType2` have different
signedness.
This can be annoying when writing template functions for arbitrary
integer types, as certain type combinations can generate useless
warnings.
Using the `sst::{f}` function instead of the plain `{o}` operator will
avoid these warnings.

The `sst::{f}` function does not have any overhead compared to the plain
`{o}` operator.

If `a` is negative or `b` is negative, the {cr_behavior_is_undefined}.

//
