//
// Copyright (C) 2012-2023 Stealth Software Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice (including
// the next paragraph) shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
// SPDX-License-Identifier: MIT
//

[#jsl-sst-sankey]
= The `sst.sankey` function

.JavaScript
[source,subs="{sst_subs_source}"]
----
{jsl_sst_sankey}(edges[, options])
----

The `{jsl_sst_sankey}` function draws a {Sankey_diagram} and returns it
as an SVG element.

A Sankey diagram is fundamentally a visualization of a weighted directed
graph.
As such, the minimum information from which a Sankey diagram can be
created is the set of edges of the graph.
The set of edges can be passed in via the `edges` parameter as an array
of triples, where each triple `[A,B,W]` means there is an edge from node
`A` to node `B` with weight `W`.
`A` and `B` should be strings, and `W` should be a number.

.{empty}
[example]
====
[source,subs="{sst_subs_source}"]
----
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<script src="d3.js"></script>
<script src="d3-sankey.js"></script>
<script src="sst/sankey.js"></script>
</head>
<body>
<script>
const edges = [
  ["A", "X", 4],
  ["A", "Y", 1],
  ["B", "X", 2],
  ["B", "Y", 3],
];
{js_document_body}.{js_appendChild}({jsl_sst_sankey}(edges));
</script>
</body>
</html>
----

++++
<script>{
  const currentScript = document.currentScript;
  window.addEventListener("DOMContentLoaded", function() {
    sst.iframeExampleOutput(currentScript, `
      <!DOCTYPE html>
      <html>
      <head>
      <meta charset="UTF-8">
      <script src="d3.js"><`+`/script>
      <script src="d3-sankey.js"><`+`/script>
      <script src="sst/sankey.js"><`+`/script>
      <`+`/head>
      <body>
      <script>
      const edges = [
        ["A", "X", 4],
        ["A", "Y", 1],
        ["B", "X", 2],
        ["B", "Y", 3],
      ];
      document.body.appendChild(sst.sankey(edges));
      <`+`/script>
      <`+`/body>
      <`+`/html>
    `);
  });
}</script>
++++
====

== `options` reference

`height`::
Specifies the height, in pixels, of the diagram.
+
The default value is `480`.

`showNodeWeights`::
Specifies whether the default node label will display the weight of the
node.
+
The default value is `false`.

`width`::
Specifies the width, in pixels, of the diagram.
+
The default value is `640`.

//
